### PR TITLE
0.7 stream updates

### PR DESCRIPTION
**Pull request by ethul**
@garyb I just have to update the README and do a bit more testing. But these changes should make the streaming possible for `pscBundle`. For the `psci` task, I just wrote the `.psci` file. Should this push out a stream instead? We can do that, but I think it works to output the file.

I will make the remaining changes tomorrow.

### CODE REVIEW

**Comment by ethul** [comment]
Okay. I realized that this is not quite ready yet in terms of the stream handling. I will push more updates on this later today.

**Comment by garyb** [comment]
Ah, sorry I haven't had a chance to look at it yet either.

The `psci` task just writing the file sounds good to me, it only works if the file is called `.psci` anyway.

**Comment by ethul** [comment]
No problem at all. Stay tuned for further updates.

**Comment by ethul** [comment]
@garyb I know this is a big switch, but I've migrated back to a stream interface for the tasks. For the `psc` task it is not too useful to have a stream. However, for `pscBundle`, `pscDocs`, and `psci`, the user can now pipe the result of the task to another stream or write the result using `gulp.dest`.

I am still looking into issue #45, but testing with gulp the errors seem to be handled okay.

What do you think?

**Comment by garyb** [comment]
Looks great! Everything works perfectly on a test project I have locally :ok_hand:. We have to pipe `psci` to `gulp.dest(".")` now, but that's not a problem at all.

Thanks very much for fixing up my mess :wink:

Do you want to fix #45 before releasing? I'd be happy for it to go out as-is if it's not a major problem, it would be good to have a non-RC version of the plugin out there that works with 0.7.

**Comment by ethul** [comment]
Thanks for taking a look and testing. Yes, we do need to pipe `psci` to `gulp.dest`, but I think the extra step is worth it for the flexibility.

And thank you for kick-starting all of these changes. #45 doesn't seem to be posing a problem in my testing so I think pushing a release as it stands now would be good. I can do a release at lunchtime today.

**Comment by garyb** [comment]
:thumbsup:

**Pull request merged**
