### PR TITLE
Enable RTS options for additional commands

### LINKED ISSUE #65: RTS options only affect compile
I'm not sure if this is a bug or intended behavior, but the RTS options passed to Gulp only have an effect on the `compile` command. We are using `-N2` to reduce problems in CircleCI, but since the RTS flags are only applied to the compile command, bundling takes almost 3 minutes.

Maybe the RTS options could be applied to bundle as well, or an option could be added to specify RTS flags when calling the plugin from JS?

### PR DESCRIPTION
**Pull request by ethul**
Resolves #65

### CODE REVIEW

**Comment by ethul** [comment]
@garyb Any feedback is definitely appreciated

**Review by garyb — APPROVED** [review]
Ah, this is a much better way to do it than my suggestion!

Was including the yarn lockfile intentional? I don't mind either way, just wanted to check.

**Comment by ethul** [comment]
Thanks for the review! And yep. The lockfile should be there. I will make a patch release.

**Comment by garyb** [comment]
Thanks :)

**Comment by ethul** [comment]
Welcome!

**Pull request merged**
