### PR TITLE
Adding support for PureScript 0.9.1 and newer

### LINKED ISSUE #59: How to add --json-errors flag?
atom ide-purescript requires that we pass --json-errors flag to psc. How do we do that in our gulpfile?

### LINKED ISSUE #60: Support PureScript 0.9.1

### PR DESCRIPTION
**Pull request by ethul**
Resolves #60 and resolves #59 

@garyb Just wondered if you had any thoughts on this PR. Thanks!

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
Skimmed through and it looks good! Only two things related to imports. Why did you explicitly write out Data.Array members when you are fully qualifiying it anyway? And you don't need to explicitly list Prelude members since you can have one implicit import per file.

**Comment by ethul** [comment]
@kRITZCREEK Thanks for taking a look!

I see you point about `Data.Array`. I suppose there is no benefit to write out the members being used since it is qualified. I can update this.

For the `Prelude`, I am thinking that it is clearer to see what is being used. Is there a drawback to writing out the members here? Or is it is not considered proper practice?

**Comment by kRITZCREEK** [comment]
No drawbacks. Just something I regularly see and do... but I actually kind of like the explicit imports here because they're few

**Comment by ethul** [comment]
Sounds good. I've updated `Data.Array`. I will push the release tonight or tomorrow. Thanks again!

**Comment by garyb** [comment]
Looks great to me :+1: 

I think Aff has been updated now too, so you should be able to use a real dependency for that.

**Comment by ethul** [comment]
Great! Thanks for taking a look. I will update the Aff dependency.

**Pull request merged**
