### PR TITLE
Add RTS options reading from argv

### PR DESCRIPTION
**Pull request by garyb**
@ethul how does this look?

### CODE REVIEW

**Comment by garyb** [comment]
Oh, I also added `--require-path` support in for `psc-bundle` and fixed a few warnings :smile:

**Comment by ethul** [comment]
@garyb Looks good! Thanks for the update. Should I merge and make a release?

**Comment by garyb** [comment]
Yes please!

**Comment by ethul** [comment]
Just noticed, I think we need the `requirePath` value added to the list in the [pscBundleOptions](https://github.com/purescript-contrib/gulp-purescript/blob/updates/src/GulpPurescript/Options.purs#L252) function. Can you please add this in to the PR?

Also, should we add any documentation about the RTS option? I was looking around and found some info on it here:
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime-control.html

However, do you think there is something else we should use. Or maybe we don't need specific documentation about it. What do you think?

**Comment by garyb** [comment]
Good catch :smile:

Yeah, I'm not sure how much documentation it need - if someone has a need to use it they're probably already familiar with the RTS options. I generally have to do a lot of looking up whenever I need to figure out how to use them too, and I've only done basic things like setting the concurrency, memory limit, and debug tracing. You're right that we should mention the fact it exists at all though.

**Comment by garyb** [comment]
Ok, I've updated the fold and docs to include the RTS info. We also had a mistake in the existing docs where `require-path` was listed under `psc-bundle` rather than `psc` - I've included it in both and updated the explanation for the `psc-bundle` usage.

**Comment by ethul** [comment]
Great! Thanks for the update and the documentation fix.

**Comment by garyb** [comment]
Thanks for the review and release!

**Comment by ethul** [comment]
Welcome, thanks for the PR

**Pull request merged**
